# Generated by Django 5.1 on 2024-08-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easygraph.graph')),
            ],
            options={
                'unique_together': {('graph', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undirected', models.BooleanField(default=True)),
                ('weight', models.IntegerField()),
                ('vertex_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='easygraph.vertex')),
                ('vertex_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='easygraph.vertex')),
            ],
            options={
                'unique_together': {('vertex_from', 'vertex_to')},
            },
        ),
    ]
