# Generated by Django 5.1 on 2024-08-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easygraph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='undirected',
        ),
        migrations.AddField(
            model_name='graph',
            name='name',
            field=models.CharField(default='demo1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='undirected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
