# Generated by Django 5.1 on 2024-08-27 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easygraph', '0002_remove_edge_undirected_graph_name_graph_undirected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='graph',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
